### ISSUE TITLE
Getting error on execution

### ISSUE THREAD

**Issue by hellofresh01** [Abdulrahman-Kamel/xssHeaders#1]
Traceback (most recent call last):
  File "C:\Users\Yaseen\Downloads\cmder\xssHeaders\scripts\func.py", line 39, in waybackurls
    writee(w_path ,'a+' , r.text)
  File "C:\Users\Yaseen\Downloads\cmder\xssHeaders\scripts\func.py", line 27, in writee
    filee = open(str(path) , str(status))
FileNotFoundError: [Errno 2] No such file or directory: 'logs/waybackurls.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Yaseen\Downloads\cmder\xssHeaders\xssHeaders.py", line 167, in <module>
    function.waybackurls(domain)
  File "C:\Users\Yaseen\Downloads\cmder\xssHeaders\scripts\func.py", line 43, in waybackurls
    writee('logs/error.txt' ,'a+' , error)
  File "C:\Users\Yaseen\Downloads\cmder\xssHeaders\scripts\func.py", line 27, in writee
    filee = open(str(path) , str(status))
FileNotFoundError: [Errno 2] No such file or directory: 'logs/error.txt'

**Comment by Abdulrahman-Kamel** [comment]
Run the tool when you are in the same directory; don't call it from another location
